In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer # use for the missing values
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [5]:
df = pd.read_csv('covid_toy.csv')

In [6]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [8]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [10]:
df.isnull().sum() # its shows the null value

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [13]:
X_train

    age  gender  fever   cough       city
95   12  Female  104.0    Mild  Bangalore
45   72    Male   99.0    Mild  Bangalore
48   66    Male   99.0  Strong  Bangalore
97   20  Female  101.0    Mild  Bangalore
63   10    Male  100.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
47   18  Female  104.0    Mild  Bangalore
53   83    Male   98.0    Mild      Delhi
26   19  Female  100.0    Mild    Kolkata
54   60  Female   99.0    Mild     Mumbai
84   69  Female   98.0  Strong     Mumbai

[80 rows x 5 columns]

# 1. Aam Zindagi

In [16]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

#also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever

array([[104.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [100.        ],
       [101.        ],
       [101.        ],
       [103.        ],
       [103.        ],
       [100.90277778],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [101.        ],
       [102.        ],
       [103.        ],
       [100.90277778],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [100.90277778],
       [ 98.        ],
       [102.        ],
       [100.90277778],
       [103.        ],
       [104.        ],
       [103.        ],
       [104.        ],
       [ 98.        ],
       [100.90277778],
       [100.90277778],
       [ 98.        ],
       [104.        ],
       [103.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [ 99.        ],
       [ 99.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [100.        ],
       [100.        ],
       [104.        ],
       [102.        ],
       [100.        ],
       [103.        ],
       [102.        ],
       [101.        ],
       [100.90277778],
       [ 99.        ],
       [100.90277778],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [101.        ],
       [102.        ],
       [104.        ],
       [104.        ],
       [101.        ],
       [101.        ],
       [102.        ],
       [104.        ],
       [104.        ],
       [100.        ],
       [104.        ],
       [102.        ],
       [102.        ],
       [101.        ],
       [ 99.        ],
       [ 99.        ],
       [104.        ],
       [ 98.        ],
       [100.        ],
       [ 99.        ],
       [ 98.        ]])

In [18]:
# Ordinal Encoding - cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

#also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [22]:
from sklearn.preprocessing import OneHotEncoder

# OneHotEncoding - gender, city
ohe = OneHotEncoder(drop='first', sparse_output=False)

X_train_gender_city = ohe.fit_transform(X_train[['gender', 'City']])

# For test data (IMPORTANT FIX BELOW)
X_test_gender_city = ohe.transform(X_test[['gender', 'City']])

print(X_train_gender_city.shape)

KeyError: "['City'] not in index"

In [23]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [25]:
import numpy as np

X_train_transformed = np.concatenate(
    (X_train_age, X_train_fever, X_train_gender_city, X_train_cough),
    axis=1
)

X_test_transformed = np.concatenate(
    (X_test_age, X_test_fever, X_test_gender_city, X_test_cough),
    axis=1
)

print(X_train_transformed.shape)

NameError: name 'X_train_gender_city' is not defined

# 2. Mentos Zindagi

In [27]:
from sklearn.compose import ColumnTransformer

In [35]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False, drop='first'),['gender', 'city'])
],remainder='passthrough')

In [37]:
transformer.fit_transform(X_train).shape

(80, 7)

In [38]:
transformer.transform(X_test).shape

(20, 7)